version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./.docker/backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development